version: '3.6'
services:
  iris:
    image: intersystemsdc/iris-community:latest
    environment:
      IRIS_USERNAME: demo
      IRIS_PASSWORD: demo
    restart: always
    hostname: iris
    ports:
      - 1972:1972
      - 52773:52773

  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      OPENAI_API_KEY: xxx
      IRIS_HOSTNAME: iris
    restart: always
    hostname: jupyter
    ports:
      - 8888:8888